name: Build & Sign APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find ZIP
        id: findzip
        run: |
          set -e
          cand=""
          for p in *.zip myapp/*.zip; do
            [ -e "$p" ] || continue
            cand="$p"; break
          done
          echo "zip=$cand" >> "$GITHUB_OUTPUT"

      - name: Unzip if ZIP present
        if: ${{ steps.findzip.outputs.zip != '' }}
        run: |
          rm -rf srcdir
          mkdir -p srcdir
          unzip -q "${{ steps.findzip.outputs.zip }}" -d srcdir
          cd srcdir
          root="."
          if [ "$(ls -1 | wc -l)" -eq 1 ] && [ -d "$(ls -1)" ]; then
            root="$(ls -1)"
          fi
          shopt -s dotglob
          mv "$root"/* ..
          cd ..
          rm -rf srcdir

      - name: Locate Gradle root
        id: gradleroot
        run: |
          if [ -f settings.gradle ] || [ -f settings.gradle.kts ]; then
            echo "dir=." >> "$GITHUB_OUTPUT"
          elif [ -f myapp/settings.gradle ] || [ -f myapp/settings.gradle.kts ]; then
            echo "dir=myapp" >> "$GITHUB_OUTPUT"
          else
            echo "Could not find settings.gradle"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        working-directory: ${{ steps.gradleroot.outputs.dir }}
        run: chmod +x ./gradlew || true

      - name: Inject signing config
        working-directory: ${{ steps.gradleroot.outputs.dir }}
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KS_PASS: ${{ secrets.KS_PASS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            mkdir -p app/keystore
            echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > app/keystore/release.keystore
            cat >> gradle.properties <<EOF
RELEASE_STORE_FILE=app/keystore/release.keystore
RELEASE_STORE_PASSWORD=$KS_PASS
RELEASE_KEY_ALIAS=$KEY_ALIAS
RELEASE_KEY_PASSWORD=$KEY_PASSWORD
kotlin.compiler.jvmTarget=11
EOF
          fi

      - name: Build Release APK
        working-directory: ${{ steps.gradleroot.outputs.dir }}
        run: ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: ${{ steps.gradleroot.outputs.dir }}/app/build/outputs/apk/release/*.apk
