name: Build and Sign APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Install Gradle (so we don't need ./gradlew)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > release_v3.keystore

      - name: Build with Gradle
        run: gradle assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKey: release_v3.keystore
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KS_PASS }}
          keyPassword: ${{ secrets.KS_PASS }}

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: AOTG_v3_signed_apk
          path: app/build/outputs/apk/release/*-signed.apk
