name: Build and Sign APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Correct action for Gradle setup
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # Run Gradle build using wrapper if available, fallback to gradle
      - name: Build Release APK
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew assembleRelease
          else
            gradle assembleRelease
          fi

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KS_PASS }}
          keyPassword: ${{ secrets.KS_PASS }}

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: AOTG_v3_signed
          path: app/build/outputs/apk/release/*-signed.apk
          if-no-files-found: error
